\title{Markdown-Pandoc-LaTeX Template}
\author{David Johnston}

\linespread{1.1}
\setlength{\parskip}{0.5em}
\setlength{\parindent}{0.0in}
\renewenvironment{quote}
                 {\list{}{\rightmargin\leftmargin}%
                  \item\relax\small}
                 {\endlist}

\usepackage{hyperref}
\hypersetup{colorlinks=false}

\usepackage{graphicx}
\usepackage{wrapfig}
\graphicspath{{Images/}}
